const $=s=>document.querySelector(s);
const shuffle=a=>{const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]}return c};
const pick=(a,n)=>shuffle(a).slice(0,n);
const norm=s=>s.normalize('NFKC').replace(/[\s　。.!！?？]/g,'');
const R=(word,reading)=>`<ruby>${word}<rt>${reading}</rt></ruby>`;
const words={
  hotel:{h:'ホテル',r:'ほてる',type:'place'},bank:{h:R('銀行','ぎんこう'),r:'ぎんこう',type:'place'},store:{h:'コンビニ',r:'こんびに',type:'place'},school:{h:R('学校','がっこう'),r:'がっこう',type:'place'},station:{h:R('駅','えき'),r:'えき',type:'place'},hospital:{h:R('病院','びょういん'),r:'びょういん',type:'place'},restaurant:{h:'レストラン',r:'れすとらん',type:'place'},room:{h:R('部屋','へや'),r:'へや',type:'place'},classroom:{h:R('教室','きょうしつ'),r:'きょうしつ',type:'place'},
  desk:{h:'つくえ',r:'つくえ',type:'large'},chair:{h:'いす',r:'いす',type:'large'},bus:{h:'バス',r:'ばす',type:'large'},car:{h:R('車','くるま'),r:'くるま',type:'large'},bag:{h:'かばん',r:'かばん',type:'small'},book:{h:R('本','ほん'),r:'ほん',type:'small'},medicine:{h:R('薬','くすり'),r:'くすり',type:'small'},phone:{h:R('電話','でんわ'),r:'でんわ',type:'small'},
  kimura:{h:`${R('木村','きむら')}さん`,r:'きむらさん',type:'living'},yamada:{h:`${R('山田','やまだ')}さん`,r:'やまださん',type:'living'},teacher:{h:R('先生','せんせい'),r:'せんせい',type:'living'},student:{h:R('学生','がくせい'),r:'がくせい',type:'living'},friend:{h:`${R('友','とも')}だち`,r:'ともだち',type:'living'},dog:{h:R('犬','いぬ'),r:'いぬ',type:'living'},cat:{h:R('猫','ねこ'),r:'ねこ',type:'living'}
};
const pos={up:{h:R('上','うえ'),r:'うえ',cell:1},down:{h:R('下','した'),r:'した',cell:7},right:{h:R('右','みぎ'),r:'みぎ',cell:5},left:{h:R('左','ひだり'),r:'ひだり',cell:3},side:{h:R('横','よこ'),r:'よこ',cell:5},front:{h:R('前','まえ'),r:'まえ',cell:7},back:{h:`${R('後','うし')}ろ`,r:'うしろ',cell:1},inside:{h:R('中','なか'),r:'なか',cell:4},outside:{h:R('外','そと'),r:'そと',cell:0},next:{h:R('隣','となり'),r:'となり',cell:5}};
const simplePool=[
  ['bank','hotel','right'],['store','hotel','front'],['bus','hotel','back'],['bag','desk','down'],['book','desk','up'],['chair','desk','left'],['phone','bag','inside'],['cat','chair','next'],['car','bank','left'],['medicine','bag','outside'],['school','station','right'],['restaurant','hotel','next'],['bag','chair','side'],['car','hotel','side']
];
const niPool=[
  ['bank','hotel','next'],['bus','hotel','front'],['store','hotel','back'],['book','bag','inside'],['cat','chair','down'],['teacher','classroom','inside'],['car','station','front'],['medicine','bag','inside'],['dog','school','outside'],['phone','desk','up'],['bag','desk','side'],['bus','hotel','side']
];
const existPool=[
  ['friend',`${R('東京','とうきょう')}に${R('友','とも')}だちが`],['restaurant','ホテルにレストランが'],['teacher',`${R('教室','きょうしつ')}に${R('先生','せんせい')}が`],['book',`つくえの${R('上','うえ')}に${R('本','ほん')}が`],['cat',`${R('部屋','へや')}に${R('猫','ねこ')}が`],['bank',`${R('駅','えき')}のとなりに${R('銀行','ぎんこう')}が`],['student',`${R('学校','がっこう')}に${R('学生','がくせい')}が`],['bus',`ホテルの${R('前','まえ')}にバスが`]
];
const restorePool=[
  {base:'hotel',items:[['bank','next'],['bus','front'],['store','back']]},
  {base:'school',items:[['station','left'],['teacher','inside'],['bus','front']]},
  {base:'desk',items:[['book','up'],['bag','down'],['chair','right']]},
  {base:'bank',items:[['car','front'],['kimura','inside'],['store','next']]}
];
const buildPool=[
  ['bank','hotel','next'],['store','bank','front'],['kimura','store','inside'],['book','desk','up'],['cat','chair','next'],['bus','station','front'],['teacher','classroom','inside'],['bag','desk','down'],['car','hotel','side']
];
const sceneInputPool=[['bank','hotel','next'],['book','desk','up'],['cat','chair','down'],['teacher','classroom','inside'],['bus','station','front'],['bag','desk','left'],['car','hotel','side']];
const koInputPool=[
  {ko:'호텔 옆에 은행이 있습니다.',a:'ほてるのとなりにぎんこうがあります'},
  {ko:'야마다 씨는 버스 안에 있습니다.',a:'やまださんはばすのなかにいます'},
  {ko:'책상 위에 책이 있습니다.',a:'つくえのうえにほんがあります'},
  {ko:'의자 옆에 고양이가 있습니다.',a:'いすのとなりにねこがいます'}
];
const stages=['위치 표현','위치와 に','あります／います','공간 복원','문장 조립','직접 입력','한국어에서 일본어로'];
let stage=0,index=0,selectedCard=null,selectedBlocks=[],restoreIndex=0;
let sets={};
function makeSets(){sets={simple:pick(simplePool,3),ni:pick(niPool,2),exist:pick(existPool,2),restore:pick(restorePool,2),build:pick(buildPool,2),sceneInput:pick(sceneInputPool,2),koInput:pick(koInputPool,1)}}
function screens(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id))}
$('#startBtn').onclick=()=>{makeSets();stage=0;index=0;screens('lesson');renderTabs();render();scrollTo(0,0)};
$('#homeBtn').onclick=$('#backBtn').onclick=()=>{screens('home');scrollTo(0,0)};
function renderTabs(){$('#tabs').innerHTML=stages.map((x,i)=>`<button class="${i===stage?'active':''}" data-i="${i}">${i+1}. ${x}</button>`).join('');$('#tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{stage=+b.dataset.i;index=0;restoreIndex=0;renderTabs();render()});$('#badge').textContent=String(stage+1).padStart(2,'0');$('#lessonTitle').textContent=stages[stage]}
function panel(title,body,count=''){return `<section class="panel"><div class="panel-head"><h3>${title}</h3>${count?`<span class="counter">${count}</span>`:''}</div>${body}</section>`}
function render(){selectedCard=null;selectedBlocks=[];if(stage===0)return renderMove(sets.simple,false);if(stage===1)return renderMove(sets.ni,true);if(stage===2)return renderExist();if(stage===3)return renderRestore();if(stage===4)return renderBuild();if(stage===5)return renderSceneInput();renderKoInput()}
function sentence(t,r,withNi){const a=words[t],b=words[r],p=pos[arguments[2]===true?arguments[3]:arguments[2]];return withNi?`${a.h}は${b.h}の${p.h}にあります。`:`${a.h}は${b.h}の${p.h}です。`}
function boardGuide(key){if(key==='front'||key==='back')return '<div class="depth-arrow" aria-hidden="true">↑<br><span>◆</span><br>↓</div>';if(key==='side'||key==='next')return '<div class="side-label left-label" aria-hidden="true">←</div><div class="side-label right-label" aria-hidden="true">→</div>';return ''}
function referenceCard(base,depth){if(depth&&words[base].type==='place')return `<div class="cube-object" aria-label="${words[base].r}"><span class="cube-top"></span><span class="cube-side"></span><span class="cube-front"><b>${words[base].h}</b><small aria-hidden="true">▥ ↓</small></span></div>`;return `<button class="place-card reference">${words[base].h}${depth?'<small class="front-mark" aria-hidden="true">▥ ↓</small>':''}</button>`}
function board(base,target,key){const depth=key==='front'||key==='back',sideways=key==='side'||key==='next',container=key==='inside'||key==='outside';let cells='';for(let i=0;i<9;i++){cells+=`<div class="zone ${i===4?'center':''}" data-cell="${i}">${i===4?referenceCard(base,depth):''}</div>`}return `<div class="space-board ${depth?'depth':''} ${sideways?'sideways':''} ${container?'container-view':''}">${boardGuide(key)}${cells}</div><div class="card-bank"><button id="moveCard" class="place-card movable" draggable="true">${words[target].h}</button></div>`}
function restoreBoard(q){const placed=q.items.slice(0,restoreIndex),current=q.items[restoreIndex],depth=current[1]==='front'||current[1]==='back',sideways=current[1]==='side'||current[1]==='next',container=current[1]==='inside'||current[1]==='outside';let cells='';for(let i=0;i<9;i++){const fixed=placed.filter(x=>pos[x[1]].cell===i).map(x=>`<button class="place-card">${words[x[0]].h}</button>`).join('');cells+=`<div class="zone ${i===4?'center':''}" data-cell="${i}">${i===4?referenceCard(q.base,depth):''}${fixed}</div>`}return `<div class="space-board ${depth?'depth':''} ${sideways?'sideways':''} ${container?'container-view':''}">${boardGuide(current[1])}${cells}</div><div class="card-bank"><button id="moveCard" class="place-card movable" draggable="true">${words[current[0]].h}</button></div>`}
function validCells(key){if(key==='side'||key==='next')return[3,5];if(key==='outside')return[0,1,2,3,5,6,7,8];return[pos[key].cell]}
function renderMove(data,withNi){const q=data[index],p=pos[q[2]],ending=words[q[0]].type==='living'?'います':'あります',text=withNi?`${words[q[0]].h}は${words[q[1]].h}の${p.h}に${ending}。`:`${words[q[0]].h}は${words[q[1]].h}の${p.h}です。`;$('#content').innerHTML=panel(withNi?'「어디에 존재한다」를 に와 함께 익혀 보세요.':'문장을 보고 카드를 알맞은 위치로 옮기세요.',`<p class="instruction">카드를 끌어 놓거나, 카드를 누른 뒤 원하는 칸을 누르세요.</p><div class="jp-sentence">${text}</div>${board(q[1],q[0],q[2])}<p id="feedback" class="feedback"></p>`,`${index+1} / ${data.length}`);wireBoard(validCells(q[2]),data)}
function wireBoard(correct,data){const valid=Array.isArray(correct)?correct:[correct],card=$('#moveCard');card.onclick=()=>{selectedCard=card;card.classList.toggle('selected')};card.ondragstart=e=>{selectedCard=card;e.dataTransfer.setData('text/plain','card')};document.querySelectorAll('.zone').forEach(z=>{z.ondragover=e=>{e.preventDefault();z.classList.add('hover')};z.ondragleave=()=>z.classList.remove('hover');z.ondrop=e=>{e.preventDefault();place(z,valid,data)};z.onclick=()=>{if(selectedCard)place(z,valid,data)}})}
function place(zone,correct,data){if(correct.includes(+zone.dataset.cell)){zone.append($('#moveCard'));$('#moveCard').classList.remove('selected');$('#moveCard').draggable=false;document.querySelectorAll('.zone').forEach(z=>z.onclick=z.ondrop=null);feedback('좋아요! 문장을 다시 천천히 읽어보세요.',true);showNext(data)}else{feedback('문장의 위치 표현을 다시 살펴보세요.',false);zone.classList.remove('hover')}}
function renderExist(){const data=sets.exist,q=data[index],living=words[q[0]].type==='living',answer=living?'います':'あります';$('#content').innerHTML=panel('사람·동물과 사물·장소의 존재 표현을 구별하세요.',`<p class="question">${q[1]}（　　　　）。</p><div class="choices"><button class="choice" data-a="あります">あります</button><button class="choice" data-a="います">います</button></div><p class="note"><b>あります</b>는 사물·장소, <b>います</b>는 사람·동물의 존재를 나타냅니다.</p><p id="feedback" class="feedback"></p>`,`${index+1} / ${data.length}`);document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{document.querySelectorAll('.choice').forEach(x=>x.disabled=true);if(b.dataset.a===answer){b.classList.add('correct');feedback(`정답입니다. ${answer}`,true)}else{b.classList.add('wrong');document.querySelector(`[data-a="${answer}"]`).classList.add('correct');feedback(`이 대상에는 ${answer}를 사용합니다.`,false)}showNext(data)})}
function renderRestore(){const data=sets.restore,q=data[index],item=q.items[restoreIndex],rows=q.items.map((x,i)=>`<div class="restore-row ${i<restoreIndex?'done':''}"><b>${i<restoreIndex?'✓':i+1}</b><span>${words[x[0]].h}は${words[q.base].h}の${pos[x[1]].h}に${words[x[0]].type==='living'?'います':'あります'}。</span></div>`).join('');$('#content').innerHTML=panel('문장을 하나씩 읽고 공간을 복원하세요.',`<div class="restore-list">${rows}</div>${restoreBoard(q)}<p id="feedback" class="feedback"></p>`,`${index+1} / ${data.length}세트`);wireBoard(validCells(item[1]),data)}
function renderBuild(){const data=sets.build,q=data[index],living=words[q[0]].type==='living',parts=[`${words[q[0]].h}は`,`${words[q[1]].h}の`,`${pos[q[2]].h}に`,living?'います':'あります'],extras=[`${pos[q[2]==='right'?'left':'right'].h}に`,living?'あります':'います'];selectedBlocks=[];$('#content').innerHTML=panel('공간 관계를 보고 문장을 순서대로 조립하세요.',`<div class="mini-scene"><span>${words[q[1]].h}</span><span class="arrow">${pos[q[2]].h}</span><span>${words[q[0]].h}</span></div><div id="answer" class="blocks">블록을 차례로 선택하세요</div><div id="bank" class="block-bank">${shuffle([...parts,...extras]).map((x,i)=>`<button class="block" data-id="${i}">${x}</button>`).join('')}</div><p id="feedback" class="feedback"></p><div class="actions"><button class="secondary" id="undo">하나 되돌리기</button><button class="primary" id="check">정답 확인</button></div>`,`${index+1} / ${data.length}`);document.querySelectorAll('.block').forEach(b=>b.onclick=()=>{if(b.classList.contains('used'))return;b.classList.add('used');selectedBlocks.push(b);showBlocks()});$('#undo').onclick=()=>{const b=selectedBlocks.pop();if(b)b.classList.remove('used');showBlocks()};$('#check').onclick=()=>{if(selectedBlocks.map(b=>b.innerHTML).join('')===parts.join('')){feedback('정답입니다. 공간의 순서와 문장의 순서를 함께 확인해 보세요.',true);document.querySelectorAll('button.block').forEach(b=>b.disabled=true);showNext(data)}else feedback('문장 순서를 다시 살펴보세요.',false)}}
function showBlocks(){$('#answer').innerHTML=selectedBlocks.length?selectedBlocks.map(b=>`<span class="block">${b.innerHTML}</span>`).join(''):'블록을 차례로 선택하세요'}
function renderSceneInput(){const data=sets.sceneInput,q=data[index],living=words[q[0]].type==='living',a=`${words[q[0]].r}は${words[q[1]].r}の${pos[q[2]].r}に${living?'います':'あります'}`;$('#content').innerHTML=panel('공간을 보고 히라가나로 문장을 입력하세요.',`<div class="mini-scene"><span>${words[q[1]].h}</span><span class="arrow">${pos[q[2]].h}</span><span>${words[q[0]].h}</span></div><p class="question">${words[q[0]].h}はどこに${living?'います':'あります'}か。</p>${inputBox('문장 입력',a,data)}`,`${index+1} / ${data.length}`);wireInput(a,data)}
function renderKoInput(){const data=sets.koInput,q=data[index];$('#content').innerHTML=panel('한국어 문장을 히라가나로 표현하세요.',`<p class="translation">${q.ko}</p>${inputBox('일본어 문장 입력',q.a,data)}`,`${index+1} / ${data.length}`);wireInput(q.a,data)}
function inputBox(label){return `<div class="input-wrap"><label for="answerInput">${label}</label><input id="answerInput" class="jp-input" lang="ja" autocomplete="off" placeholder="히라가나로 입력하세요"><p id="feedback" class="feedback"></p></div><div class="actions"><button id="checkInput" class="primary">입력 확인</button></div>`}
function wireInput(answer,data){const check=()=>{if(norm($('#answerInput').value)===norm(answer)){feedback(`정답입니다! ${answer}`,true);$('#answerInput').disabled=true;showNext(data)}else feedback('위치 표현과 に, 존재 표현을 다시 확인해 보세요.',false)};$('#checkInput').onclick=check;$('#answerInput').onkeydown=e=>{if(e.key==='Enter')check()};$('#answerInput').focus()}
function feedback(text,good){const f=$('#feedback');f.textContent=text;f.className=`feedback ${good?'good':'bad'}`}
function showNext(data){if($('#nextBtn'))return;const moreRestore=stage===3&&restoreIndex<sets.restore[index].items.length-1,last=index===data.length-1,label=moreRestore?'다음 문장 →':last?(stage===stages.length-1?'학습 마치기':'다음 단계 →'):'다음 문제 →';$('#feedback').insertAdjacentHTML('afterend',`<div class="actions"><button id="nextBtn" class="primary">${label}</button></div>`);$('#nextBtn').onclick=()=>advance(data)}
function advance(data){if(stage===3&&restoreIndex<sets.restore[index].items.length-1){restoreIndex++;render();return}restoreIndex=0;if(index<data.length-1){index++;render();return}if(stage<stages.length-1){stage++;index=0;renderTabs();render();scrollTo(0,0);return}$('#content').innerHTML=panel('학습을 마쳤습니다!',`<p class="note">공간을 움직이고 문장으로 표현하는 전 과정을 마쳤습니다. 다시 시작하면 새로운 조합이 출제됩니다.</p><div class="actions"><button class="primary" onclick="document.querySelector('#backBtn').click()">처음으로</button></div>`)}
