const R=(k,r)=>`<ruby>${k}<rt>${r}</rt></ruby>`,$=s=>document.querySelector(s);
const shuffle=a=>{const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]}return c},pick=(a,n)=>shuffle(a).slice(0,n),norm=s=>s.normalize('NFKC').replace(/[\s　。.!！?？]/g,'');
const H=['','いち','に','さん','よん','ご','ろく','なな','はち','きゅう'];
const number=n=>n<10?H[n]:n===10?'じゅう':n<20?`じゅう${H[n-10]}`:n===20?'にじゅう':`にじゅう${H[n-20]}`;
const hour=h=>{const tens=h>=20?'にじゅう':h>=10?'じゅう':'',one=h%10;if(one===4)return`${tens}よじ`;if(one===7)return`${tens}しちじ`;if(one===9)return`${tens}くじ`;return`${number(h)}じ`},time=(h,half=false)=>hour(h)+(half?'はん':'');
const showTime=(h,half=false)=>`${h}${R('時','じ')}${half?R('半','はん'):''}`;
const V=(key,jp,ko)=>({key,jp,ko});
const common={now:V('now',R('今','いま'),'지금'),whatTime:V('whatTime',R('何時','なんじ'),'몇 시'),am:V('am',R('午前','ごぜん'),'오전'),pm:V('pm',R('午後','ごご'),'오후'),half:V('half',R('半','はん'),'반·30분')};
const cities=[['tokyo',R('東京','とうきょう'),'도쿄',12],['beijing',R('北京','ペキン'),'베이징',11],['bangkok','バンコク','방콕',10],['london','ロンドン','런던',3],['la','ロサンゼルス','로스앤젤레스',19],['ny','ニューヨーク','뉴욕',22]];
const cityRead={tokyo:'とうきょう',beijing:'ペキン',bangkok:'バンコク',london:'ロンドン',la:'ロサンゼルス',ny:'ニューヨーク'};
const days=[['sun',R('日曜日','にちようび'),'일요일'],['mon',R('月曜日','げつようび'),'월요일'],['tue',R('火曜日','かようび'),'화요일'],['wed',R('水曜日','すいようび'),'수요일'],['thu',R('木曜日','もくようび'),'목요일'],['fri',R('金曜日','きんようび'),'금요일'],['sat',R('土曜日','どようび'),'토요일']];
const events=[['meeting',R('会議','かいぎ'),'회의','thu'],['exam',R('試験','しけん'),'시험','tue'],['holiday',R('休','やす')+'み','휴일','sat'],['study',R('勉強','べんきょう'),'공부','mon'],['work',R('仕事','しごと'),'일','fri']];
const places=[['bank',R('銀行','ぎんこう'),'은행',9,15],['post',R('郵便局','ゆうびんきょく'),'우체국',9,17],['library',R('図書館','としょかん'),'도서관',9,18.5],['company',R('会社','かいしゃ'),'회사',9.25,17.75],['dept','デパート','백화점',10,20.5],['hospital',R('病院','びょういん'),'병원',8.5,17.5]];
const routines=[['wake',R('起','お')+'きます','일어납니다','おきます'],['sleep',R('寝','ね')+'ます','잡니다','ねます'],['work',R('働','はたら')+'きます','일합니다','はたらきます'],['study',R('勉強','べんきょう')+'します','공부합니다','べんきょうします']];
const expressions=[['everyMorning',R('毎朝','まいあさ'),'매일 아침'],['everyNight',R('毎晩','まいばん'),'매일 밤'],['thisMorning',R('今朝','けさ'),'오늘 아침'],['tonight',R('今晩','こんばん'),'오늘 밤'],['tomorrow','あした','내일']];
const clockHtml=(h,half)=>`<div class="clock" style="--hour:${h*30+(half?15:0)}deg;--minute:${half?180:0}deg"><span class="n12">12</span><span class="n3">3</span><span class="n6">6</span><span class="n9">9</span><i class="hand hour"></i><i class="hand minute"></i><i class="pin"></i></div>`;
const units=[
 {id:1,icon:'🕰️',title:'시계 읽기',sub:'몇 시·몇 시 반을 읽어요',vocab:[common.now,common.whatTime,common.am,common.pm,V('hour',R('時','じ'),'시'),common.half]},
 {id:2,icon:'🌏',title:'세계의 현재 시각',sub:'도시의 오전·오후 시각을 말해요',vocab:[common.now,common.whatTime,common.am,common.pm,...cities.map(x=>V(x[0],x[1],x[2]))]},
 {id:3,icon:'📅',title:'요일과 일정',sub:'회의·시험·휴일의 요일을 물어요',vocab:[V('whatDay',R('何曜日','なんようび'),'무슨 요일'),...days.map(x=>V(x[0],x[1],x[2])),...events.map(x=>V(x[0],x[1],x[2]))]},
 {id:4,icon:'🏢',title:'몇 시부터 몇 시까지',sub:'장소의 이용 시간을 말해요',vocab:[common.whatTime,V('from','から','~부터'),V('until','まで','~까지'),...places.map(x=>V(x[0],x[1],x[2]))]},
 {id:5,icon:'🌅',title:'생활 시간과 과거형',sub:'언제 무엇을 하는지 현재·과거로 말해요',vocab:[...expressions.map(x=>V(x[0],x[1],x[2])),...routines.map(x=>V(x[0],x[1],x[2])),V('past',R('起','お')+'きました','일어났습니다')]}
];
let unit=units[0],phase=0,index=0,selected=[],session={};
function tParts(n){return [time(n.h,n.half),'です']}
function makeClockPool(){return Array.from({length:12},(_,i)=>[false,true].map(half=>({h:i+1,half}))).flat().map(n=>({scene:clockHtml(n.h,n.half),q:`${R('今','いま')}${R('何時','なんじ')}ですか。`,cue:`${n.h}:${n.half?'30':'00'}`,a:time(n.h,n.half),opts:[time(n.h%12+1,n.half),time((n.h+2)%12+1,!n.half),time((n.h+5)%12+1,n.half)],blocks:tParts(n),blank:n.half?{ko:`${n.h}시 30분입니다.`,jp:`${time(n.h)}<span class="blank">＿＿</span>です。`,a:'はん',done:'はん'}:{ko:`${n.h}시입니다.`,jp:`<span class="blank">＿＿</span>です。`,a:time(n.h),done:time(n.h)},full:{ko:`지금은 ${n.h}시${n.half?' 반':''}입니다.`,a:`いまは${time(n.h,n.half)}です`,done:`${R('今','いま')}は${time(n.h,n.half)}です。`}}))}
function makeWorldPool(){return cities.flatMap(c=>[false,true].map(half=>{const h=((c[3]-1)%12)+1,ampm=c[3]>=12?common.pm:common.am,digital=`${h}:${half?'30':'00'}`,meridiem=c[3]>=12?'PM':'AM';return{scene:`<strong class="digital">${meridiem} ${digital}</strong>`,q:`${c[1]}は${R('今','いま')}${R('何時','なんじ')}ですか。`,cue:`${meridiem} ${digital}`,a:`${ampm.jp}${time(h,half)}`,opts:pick(cities.filter(x=>x[0]!==c[0]).map(x=>`${x[3]>=12?common.pm.jp:common.am.jp}${time(((x[3]-1)%12)+1,false)}`),3),blocks:[ampm.jp,time(h,half),'です'],blank:{ko:`${c[2]}은 지금 몇 시입니까?`,jp:`${c[1]}は${R('今','いま')}<span class="blank">＿＿</span>ですか。`,a:'なんじ',done:R('何時','なんじ')},full:{ko:`${c[2]}은 지금 ${ampm.ko} ${h}시${half?' 반':''}입니다.`,a:`${cityRead[c[0]]}はいま${ampm.key==='am'?'ごぜん':'ごご'}${time(h,half)}です`,done:`${c[1]}は${R('今','いま')}${ampm.jp}${time(h,half)}です。`}}}))}
function makeDayPool(){return events.flatMap(e=>days.map(d=>({scene:`<strong class="cue">${d[2]}</strong>`,q:`${e[1]}は${R('何曜日','なんようび')}ですか。`,cue:d[2],a:d[1],opts:pick(days.filter(x=>x[0]!==d[0]).map(x=>x[1]),3),blocks:[e[1],'は',d[1],'です'],blank:{ko:`${e[2]}는 무슨 요일입니까?`,jp:`${e[1]}は<span class="blank">＿＿</span>ですか。`,a:'なんようび',done:R('何曜日','なんようび')},full:{ko:`${e[2]}는 ${d[2]}입니다.`,a:`${e[0]==='meeting'?'かいぎ':e[0]==='exam'?'しけん':e[0]==='holiday'?'やすみ':e[0]==='study'?'べんきょう':'しごと'}は${['にちようび','げつようび','かようび','すいようび','もくようび','きんようび','どようび'][days.indexOf(d)]}です`,done:`${e[1]}は${d[1]}です。`}})))}
const decimalTime=n=>{const h=Math.floor(n),half=n%1===.5,quarter=n%1===.25,three=n%1===.75;return{h,read:hour(h)+(half?'はん':quarter?'じゅうごふん':three?'よんじゅうごふん':''),show:`${showTime(h)}${half?R('半','はん'):quarter?`15${R('分','ふん')}`:three?`45${R('分','ふん')}`:''}`}}
function makePlacePool(){return places.flatMap(p=>[{s:p[3],e:p[4]},{s:Math.max(7,p[3]-1),e:p[4]}].map(x=>{const s=decimalTime(x.s),e=decimalTime(x.e),cue=`${Math.floor(x.s)}:${x.s%1?x.s%1===.5?'30':'15':'00'}부터 ${Math.floor(x.e)}:${x.e%1?x.e%1===.5?'30':'45':'00'}까지`;return{scene:`<strong class="cue">${cue}</strong>`,q:`${p[1]}は${R('何時','なんじ')}から${R('何時','なんじ')}までですか。`,cue,a:`${s.read}から${e.read}まで`,opts:pick(places.filter(z=>z[0]!==p[0]).map(z=>`${decimalTime(z[3]).read}から${decimalTime(z[4]).read}まで`),3),blocks:[p[1],'は',s.read,'から',e.read,'まで','です'],blank:{ko:`${p[2]}은 몇 시부터 몇 시까지입니까?`,jp:`${p[1]}は${R('何時','なんじ')}<span class="blank">＿＿</span>${R('何時','なんじ')}<span class="blank">＿＿</span>ですか。`,a:'からまで',done:'から／まで'},full:{ko:`${p[2]}은 ${Math.floor(x.s)}시부터 ${Math.floor(x.e)}시${e.half?' 반':''}까지입니다.`,a:`${p[0]==='bank'?'ぎんこう':p[0]==='post'?'ゆうびんきょく':p[0]==='library'?'としょかん':p[0]==='company'?'かいしゃ':p[0]==='hospital'?'びょういん':'デパート'}は${s.read}から${e.read}までです`,done:`${p[1]}は${s.read}から${e.read}までです。`}}}))}
function makeRoutinePool(){const hours=[6,6.5,7,7.5,8,9,10,11];return expressions.flatMap((ex,xi)=>routines.map((r,ri)=>{const h=hours[(xi+ri)%hours.length],past=ex[0]==='thisMorning',verb=past?r[3].replace('ます','ました'):r[3],cue=`${Math.floor(h)}:${h%1?'30':'00'}`,reading=time(Math.floor(h),h%1===.5);return{scene:`<strong class="cue">${cue}</strong>`,q:`${ex[1]}${R('何時','なんじ')}に${r[1].replace('ます',past?'ました':'ます')}か。`,cue,a:reading,opts:pick(hours.filter(x=>x!==h).map(x=>time(Math.floor(x),x%1===.5)),3),blocks:[ex[1],reading,'に',r[1].replace('ます',past?'ました':'ます')],blank:{ko:`${ex[2]} 몇 시에 ${r[2]}?`,jp:`${ex[1]}<span class="blank">＿＿</span>に${r[1]}か。`,a:'なんじ',done:R('何時','なんじ')},full:{ko:`${ex[2]} ${Math.floor(h)}시${h%1?' 반':''}에 ${r[2]}.`,a:`${ex[0]==='everyMorning'?'まいあさ':ex[0]==='everyNight'?'まいばん':ex[0]==='thisMorning'?'けさ':ex[0]==='tonight'?'こんばん':'あした'}${reading}に${verb}`,done:`${ex[1]}${reading}に${r[1].replace('ます',past?'ました':'ます')}。`}}}))}
function blankPool(id,pool){if(id===1)return pool.map(x=>x.blank);if(id===2)return[
 {ko:'베이징은 지금 몇 시입니까?',jp:`${R('北京','ペキン')}は${R('今','いま')}<span class="blank">＿＿</span>ですか。`,a:'なんじ',done:R('何時','なんじ')},
 {ko:'도쿄는 지금 오후 12시입니다.',jp:`${R('東京','とうきょう')}は${R('今','いま')}<span class="blank">＿＿</span>${showTime(12)}です。`,a:'ごご',done:R('午後','ごご')},
 {ko:'런던은 지금 오전 3시입니다.',jp:`ロンドンは${R('今','いま')}${R('午前','ごぜん')}<span class="blank">＿＿</span>です。`,a:'さんじ',done:showTime(3)},
 {ko:'뉴욕은 지금 몇 시입니까?',jp:`<span class="blank">＿＿</span>は${R('今','いま')}${R('何時','なんじ')}ですか。`,a:'ニューヨーク',done:'ニューヨーク'},
 {ko:'오후',jp:`<span class="blank">＿＿</span>`,a:'ごご',done:R('午後','ごご')}];
 if(id===3)return[
 {ko:'회의는 무슨 요일입니까?',jp:`${R('会議','かいぎ')}は<span class="blank">＿＿</span>ですか。`,a:'なんようび',done:R('何曜日','なんようび')},
 {ko:'회의는 목요일입니다.',jp:`${R('会議','かいぎ')}は<span class="blank">＿＿</span>です。`,a:'もくようび',done:R('木曜日','もくようび')},
 {ko:'시험은 화요일입니다.',jp:`${R('試験','しけん')}は<span class="blank">＿＿</span>です。`,a:'かようび',done:R('火曜日','かようび')},
 {ko:'토요일은 휴일입니다.',jp:`${R('土曜日','どようび')}は<span class="blank">＿＿</span>です。`,a:'やすみ',done:`${R('休','やす')}み`},
 {ko:'일요일',jp:`<span class="blank">＿＿</span>`,a:'にちようび',done:R('日曜日','にちようび')}];
 if(id===4)return[
 {ko:'은행은 몇 시부터 몇 시까지입니까?',jp:`${R('銀行','ぎんこう')}は${R('何時','なんじ')}<span class="blank">＿＿</span>${R('何時','なんじ')}<span class="blank">＿＿</span>ですか。`,a:'からまで',done:'から／まで'},
 {ko:'은행은 9시부터 3시까지입니다.',jp:`${R('銀行','ぎんこう')}は<span class="blank">＿＿</span>から${showTime(3)}までです。`,a:'くじ',done:showTime(9)},
 {ko:'도서관은 9시부터 6시 반까지입니다.',jp:`${R('図書館','としょかん')}は${showTime(9)}から<span class="blank">＿＿</span>までです。`,a:'ろくじはん',done:showTime(6,true)},
 {ko:'우체국',jp:`<span class="blank">＿＿</span>`,a:'ゆうびんきょく',done:R('郵便局','ゆうびんきょく')},
 {ko:'~까지',jp:`<span class="blank">＿＿</span>`,a:'まで',done:'まで'}];
 return[
 {ko:'매일 아침 몇 시에 일어납니까?',jp:`${R('毎朝','まいあさ')}<span class="blank">＿＿</span>に${R('起','お')}きますか。`,a:'なんじ',done:R('何時','なんじ')},
 {ko:'매일 아침 7시에 일어납니다.',jp:`${R('毎朝','まいあさ')}<span class="blank">＿＿</span>に${R('起','お')}きます。`,a:'しちじ',done:showTime(7)},
 {ko:'오늘 아침 6시에 일어났습니다.',jp:`<span class="blank">＿＿</span>${showTime(6)}に${R('起','お')}きました。`,a:'けさ',done:R('今朝','けさ')},
 {ko:'매일 밤 11시에 잡니다.',jp:`${R('毎晩','まいばん')}${showTime(11)}に<span class="blank">＿＿</span>。`,a:'ねます',done:`${R('寝','ね')}ます`},
 {ko:'공부합니다.',jp:`<span class="blank">＿＿</span>。`,a:'べんきょうします',done:`${R('勉強','べんきょう')}します`}]
}
function poolFor(id){return id===1?makeClockPool():id===2?makeWorldPool():id===3?makeDayPool():id===4?makePlacePool():makeRoutinePool()}
function prepare(){const pool=poolFor(unit.id),blanks=blankPool(unit.id,pool);session={meaning:pick(unit.vocab,Math.min(5,unit.vocab.length)),apply:pick(pool,4),blocks:pick(pool,3),blank:pick(blanks,3),full:pick(pool,1)}}
function screen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));scrollTo(0,0)}
$('#unitList').innerHTML=units.map(u=>`<button class="unit" data-id="${u.id}"><span class="num">0${u.id}</span><span class="copy"><strong>${u.icon} ${u.title}</strong><small>${u.sub}</small></span><i>›</i></button>`).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openUnit(+b.dataset.id));$('#homeBtn').onclick=$('#backBtn').onclick=()=>screen('home');
function openUnit(id){unit=units.find(u=>u.id===id);phase=0;index=0;prepare();$('#badge').textContent=`0${id}`;$('#title').textContent=unit.title;$('#subtitle').textContent=unit.sub;screen('lesson');tabs();render()}
const stages=['단어 익히기','뜻 고르기','표현 고르기','블록 조립','빈칸 입력','문장 입력'];
function tabs(){$('#tabs').innerHTML=stages.map((x,i)=>`<button class="${i===phase?'active':''}" data-step="${i}">${i+1}. ${x}</button>`).join('');document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{phase=+b.dataset.step;index=0;tabs();render()})}
function panel(title,body,count=''){return `<section class="panel"><div class="panel-head"><h3>${title}</h3>${count?`<span class="count">${count}</span>`:''}</div>${body}</section>`}
function render(){selected=[];if(phase===0)return vocab();if(phase===1)return meaning();if(phase===2)return apply();if(phase===3)return blocks();if(phase===4)return blank();full()}
function vocab(){$('#content').innerHTML=panel('먼저 단어와 한국어 뜻을 확인하세요.',`<div class="vocab-grid">${unit.vocab.map(v=>`<button class="vocab"><span class="jp">${v.jp}</span><span class="ko">${v.ko}</span></button>`).join('')}</div><p class="note">단어를 소리 내어 읽어보세요. 다음 단계부터 같은 표현이 문장 속에 나타납니다.</p><div class="actions"><button class="primary" onclick="nextPhase()">뜻 고르기 →</button></div>`)}
function meaning(){const data=session.meaning,q=data[index],opts=shuffle([q,...pick(unit.vocab.filter(v=>v.key!==q.key),3)]);$('#content').innerHTML=panel('한국어 뜻에 맞는 단어를 고르세요.',`<div class="prompt"><p>‘${q.ko}’에 해당하는 표현은?</p></div><div class="choices">${opts.map(v=>`<button class="choice" data-key="${v.key}" data-answer="${v.key===q.key?'yes':'no'}">${v.jp}</button>`).join('')}</div><p id="feedback" class="feedback"></p>`,`${index+1} / ${data.length}`);document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>checkChoice(b,b.dataset.key===q.key,data,q.jp))}
function apply(){const data=session.apply,q=data[index],opts=shuffle([q.a,...q.opts.filter((x,i,a)=>x!==q.a&&a.indexOf(x)===i).slice(0,3)]);$('#content').innerHTML=panel('그림과 질문에 맞는 표현을 고르세요.',`<div class="prompt">${q.scene}<p>${q.q}</p></div><div class="choices">${opts.map((x,i)=>`<button class="choice" data-i="${i}" data-answer="${x===q.a?'yes':'no'}">${x}</button>`).join('')}</div><p id="feedback" class="feedback"></p>`,`${index+1} / ${data.length}`);document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>checkChoice(b,b.dataset.answer==='yes',data,q.a))}
function checkChoice(b,good,data,answer){document.querySelectorAll('.choice').forEach(x=>x.disabled=true);if(good){b.classList.add('correct');feedback('정답입니다. 표현을 소리 내어 읽어보세요.',true)}else{b.classList.add('wrong');document.querySelector('[data-answer="yes"]')?.classList.add('correct');feedback(`정답은 ${strip(answer)}입니다.`,false)}showNext(data)}
function strip(s){const d=document.createElement('div');d.innerHTML=s;return d.textContent}
function blocks(){const data=session.blocks,q=data[index],answer=q.blocks,wrong=['に','から','まで','です'].filter(x=>!answer.includes(x)).slice(0,2),bank=shuffle([...answer,...wrong]);selected=[];$('#content').innerHTML=panel('질문을 읽고, 제시된 정답 방향에 맞게 조립하세요.',`<div class="prompt">${unit.id===1?q.scene:''}<p>${q.q}</p><strong class="block-cue">정답 방향: ${q.cue}</strong></div><div id="answer" class="answer-zone">블록을 차례로 선택하세요</div><div class="bank">${bank.map((x,i)=>`<button class="block" data-i="${i}">${x}</button>`).join('')}</div><p id="feedback" class="feedback"></p><div class="actions"><button class="secondary" id="undo">하나 되돌리기</button><button class="primary" id="check">정답 확인</button></div>`,`${index+1} / ${data.length}`);document.querySelectorAll('.block').forEach(b=>b.onclick=()=>{if(b.classList.contains('used'))return;b.classList.add('used');selected.push(b);showBlocks()});$('#undo').onclick=()=>{const b=selected.pop();if(b)b.classList.remove('used');showBlocks()};$('#check').onclick=()=>{if(selected.map(b=>b.innerHTML).join('')===answer.join('')){feedback('정답입니다. 완성된 문장을 읽어보세요.',true);showNext(data)}else feedback('블록의 순서를 다시 확인하세요.',false)}}
function showBlocks(){$('#answer').innerHTML=selected.length?selected.map(b=>`<span class="block">${b.innerHTML}</span>`).join(''):'블록을 차례로 선택하세요'}
function blank(){const data=session.blank,q=data[index];$('#content').innerHTML=panel('한국어 뜻을 보고 빈칸을 입력하세요.',`<p class="translation">${q.ko}</p><div class="sentence">${q.jp}</div>${inputHtml('일본어로 입력하세요')}`,`${index+1} / ${data.length}`);wireInput(q.a,data,q.done)}
function full(){const data=session.full,q=data[index].full;$('#content').innerHTML=panel('한국어 문장을 일본어로 입력하세요.',`<p class="translation">${q.ko}</p>${inputHtml('문장 전체를 히라가나로 입력하세요')}<div id="done" class="sentence" hidden></div>`,`${index+1} / ${data.length}`);wireInput(q.a,data,q.done)}
function inputHtml(ph){return `<input id="typing" class="input" lang="ja" autocomplete="off" placeholder="${ph}"><p id="feedback" class="feedback"></p><div class="actions"><button id="checkInput" class="primary">입력 확인</button></div>`}
function wireInput(answer,data,done){const valid=(Array.isArray(answer)?answer:[answer]).map(norm),check=()=>{if(valid.includes(norm($('#typing').value))){feedback('정답입니다. 문장 전체를 소리 내어 읽어보세요.',true);$('#typing').disabled=true;if($('#done')){$('#done').innerHTML=done;$('#done').hidden=false}showNext(data)}else feedback('시간 표현과 조사, 문장 끝을 다시 확인하세요.',false)};$('#checkInput').onclick=check;$('#typing').onkeydown=e=>{if(e.key==='Enter')check()};$('#typing').focus()}
function feedback(t,g){$('#feedback').textContent=t;$('#feedback').className=`feedback ${g?'good':'bad'}`}
function showNext(data){if($('#nextBtn'))return;const label=index<data.length-1?'다음 문제 →':phase<5?'다음 단계 →':'복습 마치기';$('#feedback').insertAdjacentHTML('afterend',`<div class="actions"><button id="nextBtn" class="primary">${label}</button></div>`);$('#nextBtn').onclick=()=>advance(data)}
function advance(data){if(index<data.length-1){index++;render()}else nextPhase()}
function nextPhase(){if(phase<5){phase++;index=0;tabs();render();scrollTo(0,0)}else $('#content').innerHTML=panel('단원 복습 완료!',`<p class="note">다시 들어오면 같은 학습 요소가 새로운 문제 조합으로 출제됩니다.</p><div class="actions"><button class="primary" onclick="document.querySelector('#backBtn').click()">단원 선택으로</button></div>`)}
